apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rutorrent
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: rutorrent
  serviceName: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: plex-media-server
              topologyKey: "kubernetes.io/hostname"
              namespaces:
                - plex-media-server-system
      # Container attempts to set permission on start and fails for ReadOnly files (CM, Sec)
      # So use an initContainer to stage them on /data volume before start
      initContainers:
        - name: stage-files
          image: busybox
          command: ["sh", "-c"]
          args:
            - mkdir -p /tmp/data/rtorrent;
              cp /tmp/rtlocal/.rtlocal.rc /tmp/data/rtorrent/.rtlocal.rc;
              cp /tmp/rtlocal/.rtlocal.rc /tmp/data/rtorrent/.rtorrent.rc;
          volumeMounts:
            - name: rutorrent-data
              mountPath: /tmp/data
            - name: rutorrent-rtlocal
              mountPath: /tmp/rtlocal
      containers:
        - name: rutorrent
          image: crazymax/rtorrent-rutorrent
          envFrom:
            - configMapRef:
                name: rutorrent-env-vars
          ports:
            - name: "rutorrent-web"
              containerPort: 8080
              protocol: TCP
            - name: "rutorrent-hc"
              containerPort: 8081
              protocol: TCP
            - name: "rutorrent-wd"
              containerPort: 9000
              protocol: TCP
            - name: "rutorrent-bt"
              containerPort: 57832
              protocol: TCP
            - name: "rutorrent-xml"
              containerPort: 8000
              protocol: TCP
            - name: "rutor-xml-hc"
              containerPort: 8001
              protocol: TCP
            - name: "rutor-web-hc"
              containerPort: 8081
              protocol: TCP
            - name: "rutor-wd-hc"
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: rutorrent-data
              mountPath: /data
            - name: rutorrent-fileserver
              mountPath: /datapool
      volumes:
        - name: rutorrent-data
          persistentVolumeClaim:
            claimName: rutorrent-data
        - name: rutorrent-fileserver
          persistentVolumeClaim:
            claimName: rutorrent-fileserver
        - name: rutorrent-rtlocal
          configMap:
            name: rutorrent-rtlocal
