resources:
  - resources/namespace.yml

# https://artifacthub.io/packages/helm/istio-official/istiod
helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.20.3 # https://artifacthub.io/packages/helm/istio-official/base
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
  - name: cni
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.23.3 # https://artifacthub.io/packages/helm/istio-official/cni
    releaseName: istio-cni
    namespace: istio-system
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.20.3 # https://artifacthub.io/packages/helm/istio-official/istiod
    releaseName: istiod
    namespace: istio-system
    valuesFile: values-discovery.yml
    includeCRDs: true
