namespace: mountaineers-activity-scraper

resources:
  - resources/namespace.yml
  - resources/cronjob.yml

configMapGenerator:
  - name: mountaineers-activity-scraper-script
    files:
      - files/mountaineers-activity-scraper-script.sh

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: zimmertr/mountaineers-activity-scraper
    newTag: 451050915885218e0392765eefcd8a970d7a4f45
