namespace: llama-swap-system

resources:
  - resources/namespace.yml
  - resources/persistentVolume.yml
  - resources/persistentVolumeClaim.yml

helmCharts:
  - name: llama-swap
    repo: oci://ghcr.io/mostlygeek/charts
    version: 263.0.0 # https://github.com/mostlygeek/llama-swap/releases
    releaseName: llama-swap
    namespace: llama-swap-system
    valuesFile: values.yml
