resources:
  - resources/namespace.yml

namespace: istio-gateway

# https://istio.io/latest/news/releases/
helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.29.0 # https://artifacthub.io/packages/helm/istio-official/gateway
    releaseName: gateway
    namespace: istio-gateway
    valuesFile: values.yml
    includeCRDs: true
