apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-applications
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - https://github.com/zimmertr/Kubernetes-Manifests
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appprojects
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: root-applications
  source:
    repoURL: https://github.com/zimmertr/Kubernetes-Manifests
    targetRevision: main
    path: .
    directory:
      recurse: true
      include: '**/appproject.yml'
      exclude: '{deprecated/**,**/*.disable*}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
