apiVersion: batch/v1
kind: CronJob
metadata:
  name: mountaineers-scraper
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: scraper
              image: zimmertr/mountaineers-scraper:latest
              imagePullPolicy: Always
              command: ["/bin/sh", "/scripts/script.sh"]
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: creds
                  mountPath: /data/google_cloud_credentials.json
                  subPath: google_cloud_credentials.json
                - name: script
                  mountPath: /scripts
          volumes:
            - name: data
              emptyDir: {}
            - name: creds
              secret:
                secretName: mountaineers-creds
            - name: script
              configMap:
                name: mountaineers-script
                defaultMode: 0755
