namespace: bluebird-system

helmCharts:
- name: bluebird-helm
  namespace: bluebird-system
  releaseName: bluebird
  repo: oci://registry-1.docker.io/zimmertr
  valuesFile: values.yml
  version: 0.1.4

resources:
- resources/namespace.yml
- resources/analysisTemplate.yml

configMapGenerator:
- files:
  - files/test-connection.sh
  name: test-connection-sh
  namespace: bluebird-system

generatorOptions:
  disableNameSuffixHash: true

images:
- name: zimmertr/bluebird
  newName: zimmertr/bluebird
  newTag: 0.14.12
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
