namespace: plex-media-server-system

resources:
  - resources/namespace.yml
  - resources/persistentVolume.yml
  - resources/persistentVolumeClaim.yml

commonLabels:
  app.kubernetes.io/name: plex-media-server

helmCharts:
  - includeCRDs: true
    name: plex-media-server
    namespace: plex-media-server-system
    releaseName: plex-media-server
    repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    valuesFile: values.yml
    version: 0.4.0

# The Helm Chart doesn't support disabling the dynamic config PersistentVolume.
# I do want one, but I want to statically reference a Mountpoint instead.
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: plex-media-server
      spec:
        template:
          spec:
            containers:
            - name: plex-media-server-pms
              volumeMounts:
              - name: pms-config
                mountPath: /config
        volumeClaimTemplates:
    target:
      kind: StatefulSet
      name: plex-media-server
