apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluebird
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluebird
  strategy:
    canary:
      stableService: bluebird-stable
      canaryService: bluebird-canary
      stableMetadata:
        labels:
          role: stable
      canaryMetadata:
        labels:
          role: canary
      dynamicStableScale: true
      steps:
        # - experiment:
        #     templates:
        #       - name: canary
        #         specRef: canary
        #         service:
        #           name: bluebird-experiment
        #     analyses:
        #       - name: test-connection
        #         templateName: test-connection
        #         requiredForCompletion: true
        #         args:
        #           - name: endpoint
        #             value: "https://bluebirdforecast.com/"
        #           - name: header
        #             value: "experiment: true"
        - setWeight: 33
        - setWeight: 66
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: bluebird
            routes:
              - bluebird-stable
  template:
    metadata:
      labels:
        app: bluebird
    spec:
      containers:
        - name: bluebird
          image: zimmertr/bluebird
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
