apiVersion: v1
kind: Namespace
metadata:
  name: amd-device-metrics-exporter-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
