apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bluebird-pr
  namespace: argo-system
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: zimmertr
          repo: bluebird
          labels:
            - create pr container
        requeueAfterSeconds: 150
  template:
    metadata:
      name: "bluebird-pr-{{ .number }}"
      labels:
        app-group: public
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: bluebird-pr
      destination:
        server: https://kubernetes.default.svc
        namespace: bluebird-system
      source:
        repoURL: oci://registry-1.docker.io/zimmertr/bluebird-helm
        chart: bluebird-helm
        targetRevision: 0.4.4
        helm:
          releaseName: "bluebird-pr-{{ .number }}"
          valuesObject:
            image:
              name: zimmertr/bluebird-pr
              tag: "pr-{{ .number }}-{{ .head_sha }}"
            ingress:
              enabled: true
              hosts:
                - "pr-{{ .number }}.ganymede.sol.milkyway"
            extraEnv:
              - name: PREVIEW_BANNER
                value: "true"
              - name: PREVIEW_PR
                value: "{{ .number }}"
              - name: PREVIEW_COMMIT
                value: "{{ .head_sha }}"
              - name: LOG_LEVEL
                value: "TRACE"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
