apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Radarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-fileserver
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-movies
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Movies
