apiVersion: v1
kind: PersistentVolume
metadata:
    name: jira-postgres-data
spec:
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Jira/postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: jira-data
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Jira/data
