deploymentStrategy: {"type":"Recreate"}

persistence:
  config:
    enabled: false
  media:
    enabled: false

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.40.130
  externalTrafficPolicy: Local
  type: LoadBalancer

volumes:  
  - name: jellyfin-anime
    persistentVolumeClaim:
      claimName: jellyfin-anime
  - name: jellyfin-audiobooks
    persistentVolumeClaim:
      claimName: jellyfin-audiobooks
  - name: jellyfin-cartoons
    persistentVolumeClaim:
      claimName: jellyfin-cartoons
  - name: jellyfin-cache
    persistentVolumeClaim:
      claimName: jellyfin-cache
  - name: jellyfin-config
    persistentVolumeClaim:
      claimName: jellyfin-config
  - name: jellyfin-movies
    persistentVolumeClaim:
      claimName: jellyfin-movies
  - name: jellyfin-music
    persistentVolumeClaim:
      claimName: jellyfin-music
  - name: jellyfin-tv-shows
    persistentVolumeClaim:
      claimName: jellyfin-tv-shows
  - name: jellyfin-unsorted
    persistentVolumeClaim:
      claimName: jellyfin-unsorted

volumeMounts:
  - name: jellyfin-anime
    mountPath: /anime
  - name: jellyfin-audiobooks
    mountPath: /audiobooks
  - name: jellyfin-cache
    mountPath: /cache
  - name: jellyfin-cartoons
    mountPath: /cartoons
  - name: jellyfin-config
    mountPath: /config
  - name: jellyfin-movies
    mountPath: /movies
  - name: jellyfin-music
    mountPath: /music
  - name: jellyfin-tv-shows
    mountPath: /tv_shows
  - name: jellyfin-unsorted
    mountPath: /unsorted

# jellyfin:
#   env:

# securityContext:
#   capabilities:
#     add:
#       - "SYS_ADMIN"
#     drop:
#       - "ALL"
#   privileged: false

# volumes:
  # - name: jellyfin-hardware-acceleration
  #   persistentVolumeClaim:
  #     claimName: jellyfin-hardware-acceleration
#   - name: jellyfin-transcode
#     persistentVolumeClaim:
#       claimName: jellyfin-transcode

# volumeMounts:
#   # - name: jellyfin-data
#   #   mountPath: /config
#   # - name: jellyfin-hardware-acceleration
#   #   mountPath: /hardware-acceleration