resources:
  - resources/namespace.yml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/overview/
    # https://artifacthub.io/packages/helm/argo/argo-cd?modal=changelog
    version: 9.4.9 
    namespace: argo-system
    releaseName: argocd
    valuesFile: values.yml
    additionalValuesFiles:
      - values-notifications.yml
    includeCRDs: true
