apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: personal-website
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
        - 'nix.sol.milkyway'
        - 'tjzimmerman.com'
        - 'tjzimmerman.dev'
        - 'www.tjzimmerman.com'
        - 'www.tjzimmerman.dev'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - 'nix.sol.milkyway'
        - 'tjzimmerman.com'
        - 'tjzimmerman.dev'
        - 'www.tjzimmerman.com'
        - 'www.tjzimmerman.dev'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: personal-website
