apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nfs
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
provisioner: datapool
parameters:
    archiveOnDelete: "false"
reclaimPolicy: "Retain"
