#!/bin/bash
#Script to write to InfluxDB for CyberPower UPS Satistics
#This script requires the pwrstat utility to be installed and running on the system
#Written by BarryDinpoon

#Input InfluxDB information here
DBUSER=influxdb
DBPASS=PASSWORD
DBHOST=rhea.sol.milkyway
DBPORT=8086
DBNAME=ups

while true; do

#Gather Values for statistics
LOAD=$(pwrstat -status |grep Load | cat | awk '{print $2}')
RUNTIME=$(pwrstat -status |grep Remaining | cat | awk '{print $3}')
UTILVOLT=$(pwrstat -status |grep "Utility Voltage" | cat | awk '{print $3}')
OUTVOLT=$(pwrstat -status |grep "Output Voltage" | cat | awk '{print $3}')
BATTCAP=$(pwrstat -status |grep "Battery Capacity" | cat | awk '{print $3}')
SUPPLY=$(pwrstat -status |grep "Power Supply" | cat | awk '{print $4}')
STATE=$(pwrstat -status |grep "State" | cat | awk '{print $2}')
RATING=$(pwrstat -status |grep "Rating Power" | cat | awk '{print $3}')
LOADPERCENT=$(echo "scale=2;($LOAD/$RATING)" | bc -l)

#Check Power Supply, 1 = Utility Power, 0 = Battery Power
if [ $SUPPLY == "Utility" ]; then
    SUPPLY="1"
else
    SUPPLY="0"
fi
#Check State, 1 = Normal, 0 = Other
if [ $STATE == "Normal" ]; then
    STATE="1"
else
    STATE="0"
fi

#Write out to InfluxDB
/usr/bin/curl -s -i -XPOST -u $DBUSER:$DBPASS "http://$DBHOST:$DBPORT/write?db=$DBNAME" --data-binary  "power_status,host=$HOSTNAME success=0,load=$LOAD,runtime=$RUNTIME,utility_voltage=$UTILVOLT,output_voltage=$OUTVOLT,battery_capacity=$BATTCAP,power_supply=$SUPPLY,power_state=$STATE,ups_rating=$RATING,load_percentage=$LOADPERCENT" > /dev/null

#Wait 2 seconds
sleep 2s
done
