apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-swap-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: proxmox-flashpool
  volumeName: llama-swap-models
