namespace: cloudflared-system

resources:
  - resources/namespace.yml
  - resources/deployment.yml
  - resources/poddisruptionbudget.yml

images:
  - name: cloudflare/cloudflared
    newTag: 2026.9.3 # https://github.com/cloudflare/cloudflared/releases
