apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - https://github.com/zimmertr/Kubernetes-Manifests
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
