apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sonarr-config
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: sonarr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sonarr-tv-shows
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: sonarr-tv-shows
