apiVersion: batch/v1
kind: CronJob
metadata:
  name: mountaineers-activity-scraper
  namespace: mountaineers-activity-scraper
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: scraper
              image: zimmertr/mountaineers-activity-scraper:latest
              imagePullPolicy: Always
              command: ["/bin/sh", "/scripts/mountaineers-activity-scraper-script.sh"]
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: mountaineers-activity-scraper-creds
                  mountPath: /data/google_cloud_credentials.json
                  subPath: google_cloud_credentials.json
                - name: mountaineers-activity-scraper-script
                  mountPath: /scripts
          volumes:
            - name: data
              emptyDir: {}
            - name: mountaineers-activity-scraper-creds
              secret:
                secretName: mountaineers-activity-scraper-creds
            - name: mountaineers-activity-scraper-script
              configMap:
                name: mountaineers-activity-scraper-script
                defaultMode: 0755
