resources:
  - resources/namespace.yml

helmCharts:
  - name: proxmox-cloud-controller-manager
    repo: oci://ghcr.io/sergelogvinov/charts
    version: 0.2.32 # https://github.com/sergelogvinov/proxmox-cloud-controller-manager/releases
    releaseName: proxmox-cloud-controller-manager
    namespace: proxmox-cloud-controller-manager-system
    valuesFile: values.yml
