apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr
          envFrom:
            - configMapRef:
                name: radarr-env-vars
          ports:
            - name: "http"
              containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: radarr-data
              mountPath: /config
            - name: radarr-downloads
              mountPath: /data/downloads
            - name: radarr-movies
              mountPath: /data/movies
      volumes:
        - name: radarr-data
          persistentVolumeClaim:
            claimName: radarr-data
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: radarr-downloads
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
